Add mypy type stubs
pomerium/enterprise-client pull request #1
Opened 2021-09-14 17:32 UTC by adriangb

2021-09-21 21:05 UTC, travisgroth requested changes
@adriangb Thanks for this.  Looks very useful.

Needs a tweak to generate the stubs in the right place.  Left a suggestion for this.

- can you run `make gen-python` and commit the files to your branch?  we're currently keeping the generated files in git rather than generating on demand.
- would you be able to help integrate the stubs into the packaging pipeline on the downstream python project?  I'm not clear on how to ensure they're being shipped and usable by editors.  I didn't have any luck with a casual attempt.

2021-09-21 21:05 UTC, travisgroth commented on Makefile
> +	$(PYTHON) -m grpc_tools.protoc $(INCLUDES) --experimental_allow_proto3_optional --python_out=python/pb/pomerium/pb -mypy_out=python/pb --grpc_python_out=python/pb/pomerium/pb --mypy_grpc_out=python/
```suggestion
	$(PYTHON) -m grpc_tools.protoc $(INCLUDES) --experimental_allow_proto3_optional --python_out=python/pb --mypy_out=python/pb $(DEPS_PROTOS)
	$(PYTHON) -m grpc_tools.protoc $(INCLUDES) --experimental_allow_proto3_optional --python_out=python/pb/pomerium/pb --mypy_out=python/pb/pomerium/pb --grpc_python_out=python/pb/pomerium/pb --mypy_grpc_out=python/pb/pomerium/pb $(PROTOS)
```

2021-09-21 21:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pomerium/enterprise-client?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/pomerium/enterprise-client?pullRequest=1) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Adrian Garcia Badaracco<br/>:x: adriangb<br/><hr/>**Adrian Garcia Badaracco** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pomerium/enterprise-client?pullRequest=1) it.</sub>

2021-09-21 21:45 UTC, adriangb commented
> * can you run `make gen-python` and commit the files to your branch?  we're currently keeping the generated files in git rather than generating on demand.

got it, donzo

> * would you be able to help integrate the stubs into the packaging pipeline on the downstream python project?  I'm not clear on how to ensure they're being shipped and usable by editors.  I didn't have any luck with a casual attempt.

sure, in theory there's nothing that needs to be done if using say VSCode + Pylance extension, but I'll give it a whirl and see

Also, I had to force push because CLA. Just FYI.

2021-09-22 01:49 UTC, travisgroth approved these changes

2021-09-22 01:49 UTC, merged